export const AUDIT_ACTIONS = {
  // Reservas
  SUBIR_COMPROBANTE: "SUBIR_COMPROBANTE",
  APROBAR_PAGO: "APROBAR_PAGO",
  RECHAZAR_PAGO: "RECHAZAR_PAGO",
  CANCELAR_RESERVA_ADMIN: "CANCELAR_RESERVA_ADMIN",
  RESERVA_CADUCADA_AUTOMATICA: "RESERVA_CADUCADA_AUTOMATICA",

  // Tesorería
  CREAR_MOVIMIENTO_TESORERIA: "CREAR_MOVIMIENTO_TESORERIA",
} as const;

export type AuditAction =
  (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
