/**
 * AUTH ERROR CODES — BACKEND
 * ============================================================
 * ⚠️ Estos códigos son CONTRATO PÚBLICO con el frontend
 */
export enum AuthErrorCode {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_NOT_CONFIRMED = "EMAIL_NOT_CONFIRMED",
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
  EMAIL_ALREADY_CONFIRMED = "EMAIL_ALREADY_CONFIRMED",
  INVALID_OR_EXPIRED_TOKEN = "INVALID_OR_EXPIRED_TOKEN",
  CONNECTION_ERROR = "CONNECTION_ERROR",
}
